name: 💡 Feature Request
description: Suggest a new feature or enhancement for M.A.C.E.
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!
        Please describe your idea clearly so we can evaluate and prioritize it.

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of the app does this feature relate to?
      options:
        - Compliance Builder Hub
        - Audit Builder Hub
        - Documentation Builder Hub
        - Build / Export Options
        - MDM Integration (Jamf, Intune, etc.)
        - Rule Management
        - Settings / Preferences
        - UI / UX
        - App Launch / Startup
        - Other
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe your proposed feature
      description: What would you like to see added or changed?
      placeholder: |
        I'd like to be able to...
        It could work by...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve or what does it offer?
      description: Help us understand the end goal — why is this feature valuable?
      placeholder: |
        This would help because...
        The end goal is to...
        Right now there's no way to...
    validations:
      required: true

