name: 🤝 Offer to Help
description: Volunteer to contribute to M.A.C.E. development, testing, or documentation
title: "[Help]: "
labels: ["help wanted"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for wanting to contribute to M.A.C.E.!
        Let us know a bit about yourself and how you'd like to help.

  - type: dropdown
    id: contribution_type
    attributes:
      label: How would you like to help?
      description: Select the area(s) you're interested in contributing to
      multiple: true
      options:
        - App Testing / QA
        - MDM Test Environment (Jamf, Intune, Workspace ONE, etc.)
        - Documentation
        - UI / UX Design
        - Translation / Localization
        - Other
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: Relevant Background
      description: Tell us about your experience or skills related to your offer
      placeholder: |
        e.g. I have experience with...
        I work in the field of...
        I'm familiar with...
        I have access to a ... MDM environment
    validations:
      required: true
